/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Label = string | null;
export type Value = number;
export type Type = string | null;
export type Nodes = SimulationNode[];
export type Source = string;
export type Target = string;
export type Weight = number;
export type Edges = SimulationEdge[];
/**
 * Activation function
 */
export type Activation = string | null;
/**
 * Convergence threshold
 */
export type Threshold = number | null;
/**
 * Maximum iterations
 */
export type Maxiterations = number | null;
export type Comparetobaseline = boolean | null;
export type Initialnodevalues = {
  [k: string]: number;
} | null;
export type Clampednodes = string[] | null;
export type Interventionscenario = {
  [k: string]: unknown;
} | null;
export type Promotednodes = string[] | null;
export type Activationfunction = string | null;
export type Metadata = {
  [k: string]: unknown;
} | null;

export interface SimulationInputSchema {
  nodes: Nodes;
  edges: Edges;
  activation?: Activation;
  threshold?: Threshold;
  maxIterations?: Maxiterations;
  compareToBaseline?: Comparetobaseline;
  initialNodeValues?: Initialnodevalues;
  clampedNodes?: Clampednodes;
  interventionScenario?: Interventionscenario;
  edgeRules?: unknown;
  promotedNodes?: Promotednodes;
  activationFunction?: Activationfunction;
  metadata?: Metadata;
  [k: string]: unknown;
}
export interface SimulationNode {
  id: Id;
  label?: Label;
  value: Value;
  type?: Type;
  [k: string]: unknown;
}
export interface SimulationEdge {
  source: Source;
  target: Target;
  weight: Weight;
  [k: string]: unknown;
}
