providers = ["python", "node"]

[phases.setup]
nixPkgs = ["pkgs.python312Full"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m venv /app/venv",
  "source /app/venv/bin/activate && pip install --upgrade pip",
  "source /app/venv/bin/activate && pip install -r python_sim/requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "chmod +x start.sh && ./start.sh"

