[phases.setup]
nixPkgs = ["nodejs_20", "python312", "pip"]

[phases.install]
cmds = [
  "npm install",
  "cd python_sim && python3 -m pip install -r requirements.txt && cd .."
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "chmod +x start.sh && ./start.sh"

