providers = ["python", "node"]

[phases.setup]
nixPkgs = ["pkgs.python312"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install -r python_sim/requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "chmod +x start.sh && ./start.sh"

