# generated by datamodel-codegen:
#   filename:  FCMEdge.v1.bundled.json
#   timestamp: 2025-11-14T17:07:18+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class FCMEdge(BaseModel):
    id: str = Field(..., description='Unique edge identifier')
    source: str = Field(..., description='Source node ID')
    target: str = Field(..., description='Target node ID')
    weight: float = Field(..., description='Edge weight (typically -1 to 1)')
    sourceHandle: Optional[str] = Field(
        None, description='Source handle identifier for React Flow'
    )
    targetHandle: Optional[str] = Field(
        None, description='Target handle identifier for React Flow'
    )
