# generated by datamodel-codegen:
#   filename:  FCMNode.v1.bundled.json
#   timestamp: 2025-11-14T17:07:19+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Type(Enum):
    driver = 'driver'
    regular = 'regular'
    outcome = 'outcome'


class FCMNode(BaseModel):
    id: str = Field(..., description='Unique node identifier')
    type: Type = Field(..., description='Node type')
    label: str = Field(..., description='Human-readable node label')
    value: float = Field(..., description='Initial node value')
    positionX: float = Field(..., description='X position in the visual editor')
    positionY: float = Field(..., description='Y position in the visual editor')
    color: Optional[str] = Field(None, description='Node color (hex code)')
