# generated by datamodel-codegen:
#   filename:  Model.v1.json
#   timestamp: 2025-11-14T16:55:07+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    driver = 'driver'
    regular = 'regular'
    outcome = 'outcome'


class FCMNode(BaseModel):
    id: str = Field(..., description='Unique node identifier')
    type: Type = Field(..., description='Node type')
    label: str = Field(..., description='Human-readable node label')
    value: float = Field(..., description='Initial node value')
    positionX: float = Field(..., description='X position in the visual editor')
    positionY: float = Field(..., description='Y position in the visual editor')
    color: Optional[str] = Field(None, description='Node color (hex code)')


class FCMEdge(BaseModel):
    id: str = Field(..., description='Unique edge identifier')
    source: str = Field(..., description='Source node ID')
    target: str = Field(..., description='Target node ID')
    weight: float = Field(..., description='Edge weight (typically -1 to 1)')
    sourceHandle: Optional[str] = Field(
        None, description='Source handle identifier for React Flow'
    )
    targetHandle: Optional[str] = Field(
        None, description='Target handle identifier for React Flow'
    )


class Model(BaseModel):
    id: Optional[int] = Field(None, description='Unique model identifier')
    name: str = Field(..., description='Model name')
    description: Optional[str] = Field(None, description='Model description')
    projectId: int = Field(..., description='ID of the project this model belongs to')
    nodes: Optional[List[FCMNode]] = Field([], description='Array of FCM nodes')
    edges: Optional[List[FCMEdge]] = Field([], description='Array of FCM edges')
    createdAt: Optional[datetime] = Field(
        None, description='Timestamp when model was created'
    )
    updatedAt: Optional[datetime] = Field(
        None, description='Timestamp when model was last updated'
    )
