# generated by datamodel-codegen:
#   filename:  Project.v1.json
#   timestamp: 2025-11-14T16:55:09+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class Project(BaseModel):
    id: Optional[int] = Field(None, description='Unique project identifier')
    name: str = Field(..., description='Project name')
    description: Optional[str] = Field(None, description='Project description')
    userId: Optional[int] = Field(
        None, description='ID of the user who owns this project'
    )
    createdAt: Optional[datetime] = Field(
        None, description='Timestamp when project was created'
    )
    updatedAt: Optional[datetime] = Field(
        None, description='Timestamp when project was last updated'
    )
