# generated by datamodel-codegen:
#   filename:  Scenario.v1.json
#   timestamp: 2025-11-14T16:55:10+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class SimulationNode(BaseModel):
    id: str = Field(..., description='Unique node identifier')
    label: str = Field(..., description='Human-readable node label')
    value: float = Field(..., description='Node value')


class Activation(Enum):
    sigmoid = 'sigmoid'
    tanh = 'tanh'
    relu = 'relu'
    linear = 'linear'


class SimulationParameters(BaseModel):
    activation: Optional[Activation] = Field(
        'sigmoid', description='Activation function'
    )
    threshold: Optional[float] = Field(0.001, description='Convergence threshold')
    maxIterations: Optional[int] = Field(20, description='Maximum iterations')


class SimulationResult(BaseModel):
    finalState: Dict[str, SimulationNode] = Field(
        ..., description='Final state of all nodes after simulation'
    )
    timeSeries: Dict[str, List[float]] = Field(
        ..., description='Time series data for each node'
    )
    iterations: int = Field(..., description='Number of iterations until convergence')
    converged: bool = Field(..., description='Whether the simulation converged')
    initialValues: Dict[str, float] = Field(
        ..., description='Initial values used for simulation'
    )
    baselineFinalState: Optional[Dict[str, SimulationNode]] = Field(
        None, description='Final state from baseline simulation (if comparison was run)'
    )
    baselineTimeSeries: Optional[Dict[str, List[float]]] = Field(
        None, description='Time series from baseline simulation'
    )
    baselineIterations: Optional[int] = Field(
        None, description='Iterations for baseline simulation'
    )
    baselineConverged: Optional[bool] = Field(
        None, description='Whether baseline simulation converged'
    )
    deltaState: Optional[Dict[str, float]] = Field(
        None, description='Difference between scenario and baseline final states'
    )


class Scenario(BaseModel):
    id: Optional[int] = Field(None, description='Unique scenario identifier')
    name: str = Field(..., description='Scenario name')
    description: Optional[str] = Field(None, description='Scenario description')
    modelId: int = Field(..., description='ID of the model this scenario belongs to')
    nodes: Optional[List[SimulationNode]] = Field(
        [], description='Array of simulation nodes (snapshot at scenario creation)'
    )
    initialValues: Optional[Dict[str, float]] = Field(
        {}, description='Initial node values for this scenario'
    )
    clampedNodes: Optional[List[str]] = Field(
        [], description='Node IDs that should remain clamped during simulation'
    )
    simulationParams: Optional[SimulationParameters] = Field(
        None, description='Simulation parameters for this scenario'
    )
    results: Optional[SimulationResult] = Field(
        None, description='Simulation results (populated after running simulation)'
    )
    createdAt: Optional[datetime] = Field(
        None, description='Timestamp when scenario was created'
    )
    updatedAt: Optional[datetime] = Field(
        None, description='Timestamp when scenario was last updated'
    )
