# generated by datamodel-codegen:
#   filename:  SimulationParameters.v1.bundled.json
#   timestamp: 2025-11-14T17:07:28+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Activation(Enum):
    sigmoid = 'sigmoid'
    tanh = 'tanh'
    relu = 'relu'
    linear = 'linear'


class SimulationParameters(BaseModel):
    activation: Optional[Activation] = Field(
        'sigmoid', description='Activation function'
    )
    threshold: Optional[float] = Field(0.001, description='Convergence threshold')
    maxIterations: Optional[int] = Field(20, description='Maximum iterations')
