# generated by datamodel-codegen:
#   filename:  SimulationEdge.v1.bundled.json
#   timestamp: 2025-11-14T17:07:24+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SimulationEdge(BaseModel):
    source: str = Field(..., description='Source node ID')
    target: str = Field(..., description='Target node ID')
    weight: float = Field(..., description='Edge weight')
