# generated by datamodel-codegen:
#   filename:  SimulationInput.v1.bundled.json
#   timestamp: 2025-11-14T17:07:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Node(BaseModel):
    id: str = Field(..., description='Unique node identifier')
    label: str = Field(..., description='Human-readable node label')
    value: float = Field(..., description='Node value')


class Edge(BaseModel):
    source: str = Field(..., description='Source node ID')
    target: str = Field(..., description='Target node ID')
    weight: float = Field(..., description='Edge weight')


class Activation(Enum):
    sigmoid = 'sigmoid'
    tanh = 'tanh'
    relu = 'relu'
    linear = 'linear'


class SimulationInput(BaseModel):
    nodes: List[Node] = Field(..., description='Array of FCM nodes')
    edges: List[Edge] = Field(..., description='Array of FCM edges')
    activation: Optional[Activation] = Field(
        'sigmoid', description='Activation function to use'
    )
    threshold: Optional[float] = Field(0.001, description='Convergence threshold')
    maxIterations: Optional[int] = Field(
        100, description='Maximum iterations before stopping'
    )
    compareToBaseline: Optional[bool] = Field(
        False, description='Whether to compare against baseline'
    )
    initialNodeValues: Optional[Dict[str, float]] = Field(
        None, description='Initial values for nodes (overrides node.value)'
    )
    clampedNodes: Optional[List[str]] = Field(
        None, description='Node IDs that should remain clamped during simulation'
    )
    interventionScenario: Optional[Dict[str, Any]] = Field(
        None, description='Intervention scenario configuration'
    )
    edgeRules: Optional[Dict[str, Any]] = Field(None, description='Edge-specific rules')
    promotedNodes: Optional[List[str]] = Field(None, description='Node IDs to promote')
    activationFunction: Optional[str] = Field(
        None,
        description="Alternative activation function name (deprecated, use 'activation')",
    )
    metadata: Optional[Dict[str, Any]] = Field(None, description='Additional metadata')
