# generated by datamodel-codegen:
#   filename:  SimulationResult.v1.bundled.json
#   timestamp: 2025-11-14T17:07:29+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class FinalState(BaseModel):
    id: str = Field(..., description='Unique node identifier')
    label: str = Field(..., description='Human-readable node label')
    value: float = Field(..., description='Node value')


class AdditionalProperties(BaseModel):
    id: str = Field(..., description='Unique node identifier')
    label: str = Field(..., description='Human-readable node label')
    value: float = Field(..., description='Node value')


class SimulationResult(BaseModel):
    finalState: Dict[str, FinalState] = Field(
        ..., description='Final state of all nodes after simulation'
    )
    timeSeries: Dict[str, List[float]] = Field(
        ..., description='Time series data for each node'
    )
    iterations: int = Field(..., description='Number of iterations until convergence')
    converged: bool = Field(..., description='Whether the simulation converged')
    initialValues: Dict[str, float] = Field(
        ..., description='Initial values used for simulation'
    )
    baselineFinalState: Optional[Dict[str, AdditionalProperties]] = Field(
        None, description='Final state from baseline simulation (if comparison was run)'
    )
    baselineTimeSeries: Optional[Dict[str, List[float]]] = Field(
        None, description='Time series from baseline simulation'
    )
    baselineIterations: Optional[int] = Field(
        None, description='Iterations for baseline simulation'
    )
    baselineConverged: Optional[bool] = Field(
        None, description='Whether baseline simulation converged'
    )
    deltaState: Optional[Dict[str, float]] = Field(
        None, description='Difference between scenario and baseline final states'
    )
