# generated by datamodel-codegen:
#   filename:  SimulationNode.v1.bundled.json
#   timestamp: 2025-11-14T17:07:27+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SimulationNode(BaseModel):
    id: str = Field(..., description='Unique node identifier')
    label: str = Field(..., description='Human-readable node label')
    value: float = Field(..., description='Node value')
