# generated by datamodel-codegen:
#   filename:  User.v1.bundled.json
#   timestamp: 2025-11-14T17:07:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class User(BaseModel):
    id: Optional[int] = Field(None, description='Unique user identifier')
    username: str = Field(..., description='Unique username')
    password: str = Field(
        ..., description='Hashed password (never returned in API responses)'
    )
    displayName: Optional[str] = Field(None, description="User's display name")
    role: Optional[str] = Field('user', description='User role (user, admin, etc.)')
