/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A node in the Fuzzy Cognitive Map graph
 */
export interface FCMNode {
  /**
   * Unique node identifier
   */
  id: string;
  /**
   * Node type
   */
  type: "driver" | "regular" | "outcome";
  /**
   * Human-readable node label
   */
  label: string;
  /**
   * Initial node value
   */
  value: number;
  /**
   * X position in the visual editor
   */
  positionX: number;
  /**
   * Y position in the visual editor
   */
  positionY: number;
  /**
   * Node color (hex code)
   */
  color?: string | null;
  [k: string]: unknown;
}
