/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Fuzzy Cognitive Map (FCM) model with nodes and edges
 */
export interface Model {
  /**
   * Unique model identifier
   */
  id?: number;
  /**
   * Model name
   */
  name: string;
  /**
   * Model description
   */
  description?: string | null;
  /**
   * ID of the project this model belongs to
   */
  projectId: number;
  /**
   * Array of FCM nodes
   */
  nodes?: FCMNode[];
  /**
   * Array of FCM edges
   */
  edges?: FCMEdge[];
  /**
   * Timestamp when model was created
   */
  createdAt?: string;
  /**
   * Timestamp when model was last updated
   */
  updatedAt?: string | null;
  [k: string]: unknown;
}
/**
 * A node in the FCM graph
 */
export interface FCMNode {
  /**
   * Unique node identifier
   */
  id: string;
  /**
   * Node type
   */
  type: "driver" | "regular" | "outcome";
  /**
   * Human-readable node label
   */
  label: string;
  /**
   * Initial node value
   */
  value: number;
  /**
   * X position in the visual editor
   */
  positionX: number;
  /**
   * Y position in the visual editor
   */
  positionY: number;
  /**
   * Node color (hex code)
   */
  color?: string | null;
  [k: string]: unknown;
}
/**
 * An edge connecting two nodes in the FCM graph
 */
export interface FCMEdge {
  /**
   * Unique edge identifier
   */
  id: string;
  /**
   * Source node ID
   */
  source: string;
  /**
   * Target node ID
   */
  target: string;
  /**
   * Edge weight (typically -1 to 1)
   */
  weight: number;
  /**
   * Source handle identifier for React Flow
   */
  sourceHandle?: string | null;
  /**
   * Target handle identifier for React Flow
   */
  targetHandle?: string | null;
  [k: string]: unknown;
}
