/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A node used in FCM simulation
 */
export interface SimulationNode {
  /**
   * Unique node identifier
   */
  id: string;
  /**
   * Human-readable node label
   */
  label: string;
  /**
   * Node value
   */
  value: number;
  [k: string]: unknown;
}
