/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Results from running a simulation
 */
export interface SimulationResult {
  /**
   * Final state of all nodes after simulation
   */
  finalState: {
    [k: string]: SimulationNode;
  };
  /**
   * Time series data for each node
   */
  timeSeries: {
    [k: string]: number[];
  };
  /**
   * Number of iterations until convergence
   */
  iterations: number;
  /**
   * Whether the simulation converged
   */
  converged: boolean;
  /**
   * Initial values used for simulation
   */
  initialValues: {
    [k: string]: number;
  };
  /**
   * Final state from baseline simulation (if comparison was run)
   */
  baselineFinalState?: {
    [k: string]: SimulationNode;
  };
  /**
   * Time series from baseline simulation
   */
  baselineTimeSeries?: {
    [k: string]: number[];
  };
  /**
   * Iterations for baseline simulation
   */
  baselineIterations?: number;
  /**
   * Whether baseline simulation converged
   */
  baselineConverged?: boolean;
  /**
   * Difference between scenario and baseline final states
   */
  deltaState?: {
    [k: string]: number;
  };
  [k: string]: unknown;
}
/**
 * A node used in FCM simulation
 */
export interface SimulationNode {
  /**
   * Unique node identifier
   */
  id: string;
  /**
   * Human-readable node label
   */
  label: string;
  /**
   * Node value
   */
  value: number;
  [k: string]: unknown;
}
