/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An edge used in FCM simulation (simplified version without React Flow handles)
 */
export interface SimulationEdge {
  /**
   * Source node ID
   */
  source: string;
  /**
   * Target node ID
   */
  target: string;
  /**
   * Edge weight
   */
  weight: number;
  [k: string]: unknown;
}
