/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User account in MettaModeler
 */
export interface User {
  /**
   * Unique user identifier
   */
  id?: number;
  /**
   * Unique username
   */
  username: string;
  /**
   * Hashed password (never returned in API responses)
   */
  password: string;
  /**
   * User's display name
   */
  displayName?: string | null;
  /**
   * User role (user, admin, etc.)
   */
  role?: string;
  [k: string]: unknown;
}
